import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Poppins } from 'next/font/google'
import "./globals.css";
import HeroParallax from "@/components/HeroParallaxDemo";
import FlipWordsDemo from "@/components/FlipWordsDemo";
import { HeroHighlightDemo } from "@/components/HeroHighlightDemo";
import BackgroundBeamsDemo from "@/components/BackgroundBeamsDemo";
import { AnimatedPinDemo } from "@/components/AnimatedPinDemo";
import { TracingBeamDemo } from "@/components/TracingBeamDemo";
import EvervaultCard  from "@/components/EvervaultCardDemo";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Soumen Bhunia | Portfolio",
  description: "Generated by Soumen Bhunia , a software engineer who specializes in building (and occasionally designing) exceptional digital experiences.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      
    <body  className={Poppins.className}>
      
      <div className="mx-auto max-w-6xl py-32 sm:py-10 lg:py-10">
        <HeroHighlightDemo/>
        <HeroParallax/>
        <div className="flex">
        <AnimatedPinDemo/>
        <EvervaultCard/>
        </div>
        
        <TracingBeamDemo/>
        <BackgroundBeamsDemo/>
      </div>
      
      {children}
    </body>
  </html>
  );
}
